version: '3'
services:
  #################### Base  ####################

  base: &base
    image: darthjee/slim_jim
    volumes:
      - ./source:/home/app/app

  base_build:
    <<: *base
    build: .
    command: echo done
  #################### CONTAINERS ####################

  slim_jim:
    <<: *base
    container_name: slim_jim
    command: /bin/bash
    depends_on: [base_build]
