resimulate: false
jobs:
  - data_file: 'population'
    data:
      min_population: 1000000
      max_population: 180000000
      population_points: 50
      activation: 0.01
      mutation: 0.01
      infection: 0.01
      repetitions: 30
    plots:
      template: 'mutation'
      output: 'population'
      xlabel: 'Population Size'
      ylabel: 'Log(VaccinatedMutation/InfectedMutation)'
      x_column: 4
      y_column: 12
  - data_file: 'infection'
    data:
      population: 1000000
      activation: 0.01
      mutation: 0.01
      min_infection: 0.01
      max_infection: 1
      infection_points: 50
      repetitions: 30
    plots:
      template: 'mutation'
      output: 'infection'
      xlabel: 'Max infection'
      ylabel: 'Log(VaccinatedMutation/InfectedMutation)'
      x_column: 1
      y_column: 12
  - data_file: 'mutation'
    data:
      population: 1000000
      activation: 0.01
      min_mutation: 0.0001
      max_mutation: 1
      mutation_points: 50
      infection: 0.5
      repetitions: 30
    plots:
      template: 'mutation'
      output: 'mutation'
      xlabel: 'Mutation chance'
      ylabel: 'Log(VaccinatedMutation/InfectedMutation)'
      x_column: 2
      y_column: 12
  - data_file: 'activation'
    data:
      population: 1000000
      min_activation: 0.0001
      max_activation: 1
      activation_points: 50
      mutation: 0.01
      infection: 0.5
      repetitions: 30
    plots:
      template: 'mutation'
      output: 'activation'
      xlabel: 'Activation chance'
      ylabel: 'Log(VaccinatedMutation/InfectedMutation)'
      x_column: 3
      y_column: 12
  - plots:
      - template: 'mutation_infection_log'
        output: 'mutation_infection_0.1'
        infection: 0.1
        xrange: [0,1]
        yrange: [0,1]
      - template: 'mutation_infection_log'
        output: 'mutation_infection_0.1_cut'
        infection: 0.1
        xrange: [0,0.5]
        yrange: [0,0.5]
      - template: 'mutation_infection_log'
        output: 'mutation_infection_0.3'
        infection: 0.3
        xrange: [0,1]
        yrange: [0,1]
      - template: 'mutation_infection_log'
        output: 'mutation_infection_0.3_cut'
        infection: 0.3
        xrange: [0,0.5]
        yrange: [0,0.5]
      - template: 'mutation_infection_log'
        output: 'mutation_infection_0.5'
        infection: 0.5
        xrange: [0,1]
        yrange: [0,1]
      - template: 'mutation_infection_log'
        output: 'mutation_infection_0.5_cut'
        infection: 0.5
        xrange: [0,0.5]
        yrange: [0,0.5]
      - template: 'mutation_infection_log'
        output: 'mutation_infection_0.7'
        infection: 0.7
        xrange: [0,1]
        yrange: [0,1]
      - template: 'mutation_infection_log'
        output: 'mutation_infection_0.7_cut'
        infection: 0.7
        xrange: [0,0.5]
        yrange: [0,0.5]
