resimulate: false
jobs:
  - data_file: 'population'
    data:
      min_population: 1000000
      max_population: 180000000
      population_points: 5
      activation: 0.01
      mutation: 0.01
      infection: 0.01
      repetitions: 5
    plots:
      template: 'mutation'
      output: 'population'
      xlabel: 'Population Size'
      ylabel: 'Log(VaccinatedMutation/InfectedMutation)'
      x_column: 4
      y_column: 12
  - data_file: 'infection'
    data:
      population: 1000000
      activation: 0.01
      mutation: 0.01
      min_infection: 0.01
      max_infection: 1
      infection_points: 5
      repetitions: 5
    plots:
      template: 'mutation'
      output: 'infection'
      xlabel: 'Max infection'
      ylabel: 'Log(VaccinatedMutation/InfectedMutation)'
      x_column: 1
      y_column: 12
  - data_file: 'mutation'
    data:
      population: 1000000
      activation: 0.01
      min_mutation: 0.0001
      max_mutation: 1
      mutation_points: 5
      infection: 0.5
      repetitions: 5
    plots:
      template: 'mutation'
      output: 'mutation'
      xlabel: 'Mutation chance'
      ylabel: 'Log(VaccinatedMutation/InfectedMutation)'
      x_column: 2
      y_column: 12
  - data_file: 'activation'
    data:
      population: 1000000
      min_activation: 0.0001
      max_activation: 1
      activation_points: 5
      mutation: 0.01
      infection: 0.5
      repetitions: 5
    plots:
      template: 'mutation'
      output: 'activation'
      xlabel: 'Activation chance'
      ylabel: 'Log(VaccinatedMutation/InfectedMutation)'
      x_column: 3
      y_column: 12
