# frozen_string_literal: true

source 'https://rubygems.org'

ruby '2.5.0'

gem 'activesupport', '5.2.5', require: false
gem 'bundler', '~> 1.16.1'
gem 'danica', '2.7.5'
gem 'dr_light', '0.0.3'
gem 'rake',    '13.0.1'
gem 'rubocop', '0.80.1'
gem 'sinclair', '1.6.7'
